//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApplication99.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDBWCF")]
    public interface IDBWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBWCF/getEmployee", ReplyAction="http://tempuri.org/IDBWCF/getEmployeeResponse")]
        System.Data.DataSet getEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBWCF/getEmployee", ReplyAction="http://tempuri.org/IDBWCF/getEmployeeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getEmployeeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBWCFChannel : WebServiceApplication99.ServiceReference1.IDBWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBWCFClient : System.ServiceModel.ClientBase<WebServiceApplication99.ServiceReference1.IDBWCF>, WebServiceApplication99.ServiceReference1.IDBWCF {
        
        public DBWCFClient() {
        }
        
        public DBWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getEmployee() {
            return base.Channel.getEmployee();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getEmployeeAsync() {
            return base.Channel.getEmployeeAsync();
        }
    }
}
