//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empID { get; set; }
        public string empName { get; set; }
        public string empDept_no { get; set; }
    }
}
