//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceDB.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmember", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSmember();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmember", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSmemberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SaveData(int Eid, string Ename, int Edept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveData", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SaveDataAsync(int Eid, string Ename, int Edept);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebServiceDB.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebServiceDB.ServiceReference1.WebService1Soap>, WebServiceDB.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetSmember() {
            return base.Channel.GetSmember();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSmemberAsync() {
            return base.Channel.GetSmemberAsync();
        }
        
        public int SaveData(int Eid, string Ename, int Edept) {
            return base.Channel.SaveData(Eid, Ename, Edept);
        }
        
        public System.Threading.Tasks.Task<int> SaveDataAsync(int Eid, string Ename, int Edept) {
            return base.Channel.SaveDataAsync(Eid, Ename, Edept);
        }
    }
}
